[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  NODE_VERSION = "18.12.1"
  YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"
  YARN_VERSION = "3.3.1"
  NPM_VERSION = "8.1.3"
  YARN_FLAGS = "--no-ignore-optional"


